# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya', '~> 14.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'Moya-ObjectMapper/RxSwift'
pod 'RxCocoa', '~> 5.1.1'
pod 'RxSwift', '~> 5.1.1'
pod 'RxOptional'
  # Pods for API_Practice

end
