# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaverMap_Pracite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'NMapsMap'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'RxSwift', '~> 5.1.1'
    pod 'RxCocoa', '~> 5.1.1'
    pod 'RxDataSources'
    pod 'Kingfisher'
    pod 'RxViewController'
    pod 'RxOptional'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'AlamofireImage', '~> 4.1.0'

  # Pods for NaverMap_Pracite

end
